# Generated by Django 2.2.7 on 2022-12-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'superuser'), (1, 'Admin'), (2, 'Seller'), (3, 'Buyer')], default=3),
        ),
    ]
